import Head from 'next/head'
import { add } from '../../../../packages/wasm'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h3 data-testid="wasm">
          Wasm add function reports that 1 + 1 = {add(1, 1)}
        </h3>
      </main>
    </>
  )
}
